version: "3"
services:
  db:
    image: postgres
    container_name: db

    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: good_password

  ruby_with_sassc:
    image: ruby_with_sassc:latest
    container_name: ruby_with_sassc
    build:
      context: ./
      dockerfile: ./BattleField/Dockerfile.base_gems

  web_server:
    image: battle_field_web_server
    container_name: battle_field_web_server
    depends_on: 
      - db
    volumes:
      - /home/docker/work/BattleField:/myapp 
    ports:
      - 3000:3000
    environment:
      db_host:            db
    environment:
      db_user_name:       postgres
    environment:
      db_password:        good_password
    environment:
      database_name_dev:  battle_field_dev
    environment:
      database_name_test: battle_field_test
    environment:
      database_name:      battle_field
    environment:
      RAILS_MAX_THREADS:  5 

    build:
      context: ./BattleField/
      dockerfile: ./Dockerfile

  web_adele:
    image: battle_field_web_server
    volumes:
      - /home/adele/work/BattleField:/myapp
    ports:
      - 3001:3000
    depends_on:
      - db
  
  web_oscar:
    image: battle_field_web_server
    volumes:
      - ./oscar:/myapp
    ports:
      - 3002:3000
    depends_on:
      - db
  
  web_steven:
    image: battle_field_web_server
    volumes:
      - ./steven:/myapp
    ports:
      - 3003:3000
    depends_on:
      - db  
    # build: 
    #   context: ./ 
      
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

